### Root
GET  http://localhost:3000
### Get all products
GET http://localhost:3000/api/products

### Get Products by type
GET http://localhost:3000/api/products/?type=drinks

### Get one product
GET http://localhost:3000/api/products/69aec52dc964f514c51ebd99

### Add a product
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Mango Bubble Berry Tea",
  "price": 3.25,
  "type": "drinks",
  "category": "iced-tea",
  "url": ""
}
###
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Caramel Latte",
  "price": 4.95,
  "type": "drinks",
  "category": "hot-coffee"
}
### Update a product
PUT http://localhost:3000/api/products/69aebce1c596aec116a49566
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFlZjgzMjU5NDA4ODBkYjFlNGY2ZWQiLCJ1c2VybmFtZSI6IkhhYmVldGVjaCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3NTY4NDYzNCwiZXhwIjoxNzc1Njg4MjM0fQ.WphRM4gAEOJFWFoaOENk2bACm4aJQmnm3UwR5dxBx2I
Content-Type: application/json

{
  "url": "/latte.webp"
}

### Delete a product
DELETE http://localhost:3000/api/products/69aec52dc964f514c51ebd99