### Get all orders
GET http://localhost:3000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFlZjgzMjU5NDA4ODBkYjFlNGY2ZWQiLCJ1c2VybmFtZSI6IkhhYmVldGVjaCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3NjgwMTI3MywiZXhwIjoxNzc2ODAzMDczfQ.4PlZKiZUpl_Ip9cofKeFFosaingEWog4EV4jBDA2vjg
### "69e63a13b18a9f179521bab5"
GET http://localhost:3000/api/orders/mine
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFlZjgzMjU5NDA4ODBkYjFlNGY2ZWQiLCJ1c2VybmFtZSI6IkhhYmVldGVjaCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3NjY5ODQxMywiZXhwIjoxNzc2NzAwMjEzfQ.jV_3LWEWl_twIcAP5Qzlnsl_uWFRs7JDTt_wja-RV4A
### Pay on collection
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "items": [
    {
      "_id": "69aec52dc964f514c51ebd99",
      "name": "Mango Bubble Berry Tea",
      "url": "https://yourdomain.com/path/to/images/mango.png",
      "price": 4.50,
      "basePrice": 5.50,
      "quantity": 1,
      "type": "drinks",
      "category": "iced-tea",
      "options": {}
    }
  ],
  "total": 5.50,
  "customer": {
    "firstName": "Habeeb",
    "lastName": "Ola",
    "email": "example@email.com",
    "deliveryOption": "collection",
    "address": {}
  },
  "status": "pending",
  "paymentMethod": "collection",
  "stripeId": ""
}
### Stripe Payment
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "items": [
    {
      "_id": "69aec52dc964f514c51ebd99",
      "name": "Mango Bubble Berry Tea",
      "url": "https://yourdomain.com/path/to/images/mango.png",
      "price": 4.50,
      "basePrice": 5.50,
      "quantity": 1,
      "type": "drinks",
      "category": "iced-tea",
      "options": {}
    }
  ],
  "total": 5.50,
  "customer": {
    "firstName": "Habeeb",
    "lastName": "Ola",
    "email": "example@email.com",
    "deliveryOption": "collection",
    "address": {}
  },
  "status": "pending",
  "paymentMethod": "stripe",
  "stripeId": "pi_3TJdIqIzM8ZcbdVL12r6OrDm"
}
### Patch: Link Order ID to Stripe Payment Intent
PATCH http://localhost:3000/api/payment-intent/update
Content-Type: application/json

{
    "orderId": "69aec52dc964f514c51ebd99",
    "paymentId": "pi_3TJdIqIzM8ZcbdVL12r6OrDm"
}

### Manually set order to paid to trigger React polling update
PATCH http://localhost:3000/api/orders/6a061cf6ed8ccef17c627f47
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFlZjgzMjU5NDA4ODBkYjFlNGY2ZWQiLCJ1c2VybmFtZSI6IkhhYmVldGVjaCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3ODc4NDU3MCwiZXhwIjoxNzc4Nzg2MzcwfQ.o1IMYpSsALv0VeTOJ-lQBNLeLaTYN8heaxg-7nJtTkY
Content-Type: application/json

{
    "status": "paid"
}

###
GET http://localhost:3000/api/orders/69ea3365d56ba9db7570d997
###
DELETE http://localhost:3000/api/orders/6a0613a7ed8ccef17c627eb5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFlZjgzMjU5NDA4ODBkYjFlNGY2ZWQiLCJ1c2VybmFtZSI6IkhhYmVldGVjaCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3ODc4MjYxNSwiZXhwIjoxNzc4Nzg0NDE1fQ.IEJbNhxERMtTMpXspF0kSxoODGRjcNSUaT95i8KZXmg
