### Get all orders
GET http://localhost:3000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFlZjgzMjU5NDA4ODBkYjFlNGY2ZWQiLCJ1c2VybmFtZSI6IkhhYmVldGVjaCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3NTU5NTQ1NiwiZXhwIjoxNzc1NTk5MDU2fQ.e-vc7M3TUIQ_kLJ4ChW_qSEye6HtBOtO8jk_cuRI8Dg

### Pay on collection
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "items": [
    {
      "_id": "69aec52dc964f514c51ebd99",
      "name": "Mango Bubble Berry Tea",
      "url": "https://yourdomain.com/path/to/images/mango.png",
      "price": 4.50,
      "basePrice": 5.50,
      "quantity": 1,
      "type": "drinks",
      "category": "iced-tea",
      "options": {}
    }
  ],
  "total": 5.50,
  "customer": {
    "firstName": "Habeeb",
    "lastName": "Ola",
    "email": "example@email.com",
    "deliveryOption": "collection",
    "address": {}
  },
  "status": "pending",
  "paymentMethod": "collection",
  "stripeId": ""
}
### Stripe Payment
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "items": [
    {
      "_id": "69aec52dc964f514c51ebd99",
      "name": "Mango Bubble Berry Tea",
      "url": "https://yourdomain.com/path/to/images/mango.png",
      "price": 4.50,
      "basePrice": 5.50,
      "quantity": 1,
      "type": "drinks",
      "category": "iced-tea",
      "options": {}
    }
  ],
  "total": 5.50,
  "customer": {
    "firstName": "Habeeb",
    "lastName": "Ola",
    "email": "example@email.com",
    "deliveryOption": "collection",
    "address": {}
  },
  "status": "pending",
  "paymentMethod": "stripe",
  "stripeId": "pi_3TJdIqIzM8ZcbdVL12r6OrDm"
}
### Patch: Link Order ID to Stripe Payment Intent
PATCH http://localhost:3000/api/payment-intent/update
Content-Type: application/json

{
    "orderId": "69aec52dc964f514c51ebd99",
    "paymentId": "pi_3TJdIqIzM8ZcbdVL12r6OrDm"
}