### Root
GET  http://localhost:3000
### Get all drinks
GET http://localhost:3000/api/drinks

### Get one drink
GET http://localhost:3000/api/drinks/14

### Add a drink
POST http://localhost:3000/api/drinks
Content-Type: application/json

{
  "name": "Breakfast Tea",
  "price": 2.25,
  "category": "tea",
  "url": ""
}

### Update a drink
PUT http://localhost:3000/api/drinks/30
Content-Type: application/json

{
  "name": "Mocha Deluxe",
  "price": 4.95
}

### Delete a drink
DELETE http://localhost:3000/api/drinks/3