### Root
GET  http://localhost:3000
### Get all drinks
GET http://localhost:3000/api/drinks

### Get one drink
GET http://localhost:3000/api/drinks/1

### Add a drink
POST http://localhost:3000/api/drinks
Content-Type: application/json

{
  "name": "Mango Bubble Berry Tea",
  "price": 3.25,
  "category": "iced-tea",
  "url": ""
}
###
POST http://localhost:3000/api/drinks
Content-Type: application/json

{
  "name": "Caramel Latte",
  "price": 4.95,
  "category": "hot-coffee"
}
### Update a drink
PUT http://localhost:3000/api/drinks/69a9b70bd577d50595a5ffc0
Content-Type: application/json

{
  "name": "Caramel Latte",
  "price": 4.95
}

### Delete a drink
DELETE http://localhost:3000/api/drinks/69a9b70bd577d50595a5ffc0