
### Get all crisps
GET http://localhost:3000/api/crisps

### Get one crisp
GET http://localhost:3000/api/crisps/69adecb85c5e3d4cc186cd00

### Add a crisp
POST http://localhost:3000/api/crisps
Content-Type: application/json

{
  "name": "Popchips Barbeque",
  "price": 1.49,
  "url": ""
}
###
POST http://localhost:3000/api/crisps
Content-Type: application/json

{
  "name": "Proper Corn",
  "price": 1.05,
  "url": ""
}
### Update a crisp
PUT http://localhost:3000/api/crisps/69adecb85c5e3d4cc186cd00
Content-Type: application/json

{
  "price": 1.45
}

### Delete a crisp
DELETE http://localhost:3000/api/crisps/69adecb85c5e3d4cc186cd00