
### Get all buscuits
GET http://localhost:3000/api/buscuits

### Get one buscuit
GET http://localhost:3000/api/buscuits/69ade99149714da8019141ea

### Add a buscuit
POST http://localhost:3000/api/buscuits
Content-Type: application/json

{
  "name": "Gluten Free Brownie",
  "price": 1.99,
  "url": ""
}
###
POST http://localhost:3000/api/buscuits
Content-Type: application/json

{
  "name": "Gluten Free Millionaire Shortbread",
  "price": 2.05,
  "url": ""
}
### Update a cake
PUT http://localhost:3000/api/buscuits/69ade99149714da8019141ea
Content-Type: application/json

{
  "price": 2.15
}

### Delete a cake
DELETE http://localhost:3000/api/buscuits/69ade99149714da8019141ea